name: Build and Deploy

on:
  push:
    branches:
      - master
  schedule:
     - cron: '0/30 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: npm install
    - run: npm run gen
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: custom
        COMMIT_MESSAGE: Bump host
      env:
        CI: true
